// <auto-generated />
using IT_StudioTestTask;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IT_StudioTestTask.Migrations.AppDB2ContentMigrations
{
    [DbContext(typeof(AppDB2Content))]
    [Migration("20220521111508_seventh")]
    partial class seventh
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("IT_StudioTestTask.Models.CopyPhoto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("photosId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("photosId");

                    b.ToTable("CopyPhoto");
                });

            modelBuilder.Entity("IT_StudioTestTask.Models.Photos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("CopyCheck")
                        .HasColumnType("bit");

                    b.Property<string>("Disription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageSrc")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Photos");
                });

            modelBuilder.Entity("IT_StudioTestTask.Models.CopyPhoto", b =>
                {
                    b.HasOne("IT_StudioTestTask.Models.Photos", "photos")
                        .WithMany()
                        .HasForeignKey("photosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("photos");
                });
#pragma warning restore 612, 618
        }
    }
}
